name: Mirror to GitLab

on:
  push:
    branches:
      - '**'
  delete:
    branches:
      - '**'

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Sync Repository
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Скачиваем всю историю

      - name: Push to GitLab via HTTPS Token
        run: |
          GITLAB_URL="https://oauth2:${{ secrets.GITLAB_PROJECT_TOKEN }}@git.meiji.media/opora/opora.git"

          git remote add gitlab "$GITLAB_URL"

          # Пушим все ветки и теги без флага --prune
          git push gitlab --all
          git push gitlab --tags
